Check if you need to create a folder before creating a file to avoid errors.
Parent directory must exist before creating asset at Assets/Resources/GitHash.asset.
UnityException: Creating asset at path Assets/Resources/GitHash.asset failed.

Parent directory must exist before creating asset at Assets/Resources/GitHash.asset.
UnityException: Creating asset at path Assets/Resources/GitHash.asset failed.